const CONFIG = {
  SETTINGS: "⚙️Settings",
  DATE_PREFIX: "D",
  PROJECT_ID_PROP: "LastProjectId",
  METADATA_PROP: "Metadata",
  CONTRACT_META_PROP: "ContractMetaData",
  CONTRACT_TEMPLATE: "1n9mabMMM4DF8I54wxuczl8us85sfQ-VT2BvTAQUzYpI", //'136toZMz-Bau1Y6vvbwmxsLgFFNgzM1tWb1RfwpZ_jmE',
  CONTRACT_OUTPUT_FOLDER: "1r9INUZVhcIZ7mjXrWMXAd6Eye5RbWQoH",
  CONTRACT_ALTERNATE_COLORS: {
    color1: "#FFFFFF",
    color2: "#F3EFEF",
  },
};

class User {
  constructor() {
    this.settings = _getSettings_(CONFIG.SETTINGS);
    this.ss = SpreadsheetApp.getActive();
    this.ws = this.ss.getSheetByName(this.settings.sheetNameUsers);
  }

  getAllUsers() {
    return _getItemsFromSheet_(
      this.ss.getSheetByName(this.settings.sheetNameUsers)
    );
  }

  emailUser(values, password) {
    const [name, email, role] = values.slice(3);
    const subject = `You've been invited to ${this.settings.appName}`;
    const htmlBody = `
			<p>Welcome ${name},</p>
			<p>You've been invited to user our ${this.settings.appName}!</p>
			<p>
				Role: ${role}<br/>
				Email: ${email}<br/>
				Password: ${password}<br/>
				App: ${this.settings.urlApp}
			</p>

			<p style="color: #64596F;">
				<small>
					${this.settings.appName}<br>
					<a href="https://www.ceedcivil.com/" target="_blank" style="color: #A482B6">www.ceedcivil.com</a>
				</small>
			</p>
		`;
    const options = {
      name: this.settings.appName,
      htmlBody,
    };
    GmailApp.sendEmail(email, subject, "", options);
  }

  createUser(name, email, role, password) {
    password = password || _generatePassword_(6);
    const id = Utilities.getUuid();
    const createdAt = new Date().toISOString();
    const hashedPassword = _hashPassword_(
      password,
      this.settings.secretPasswordHash
    );
    const values = [
      id,
      createdAt,
      createdAt,
      name,
      email,
      role,
      "Active",
      hashedPassword,
    ];
    this.ws.appendRow(values);
    this.emailUser(values, password);
  }

  addNewUser() {
    const title = "+ New User";
    const ui = _getUi_();

    let msg = `What's the name of the new user (required)?`;
    const nameInput = _prompt_(msg, title);
    if (nameInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    const name = nameInput.getResponseText().trim();
    if (!name) {
      msg = "🔴 The name of the user is required!";
      return _alert_(msg, title);
    }

    msg = `What's the role of the new user (required)?

      Option 1: Admin
      Option 2: Employee (default)
      `;
    const roleInput = _prompt_(msg, title);
    if (roleInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    let role = roleInput.getResponseText().trim().toLowerCase();
    if (role == "1" || role === "admin") {
      role = "Admin";
    } else {
      role = "Employee";
    }

    msg = `What's the email address of the new user (required)?`;
    const emailInput = _prompt_(msg, title);
    if (emailInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    const email = emailInput.getResponseText().trim();
    if (!email) {
      msg = "🔴 The name of the user is required!";
      return _alert_(msg, title);
    } else if (email.indexOf("@") <= 0) {
      msg = "🔴 Invalid email address!";
      return _alert_(msg, title);
    }

    msg = `What's the password of the new user (optional)?`;
    const passwordInput = _prompt_(msg, title);
    if (passwordInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    const password = passwordInput.getResponseText().trim();

    msg = `Are you sure to add this new user?

      Name: ${name}
      Email: ${email}
      Role: ${role}
      Password: ${password || "will be generated by the script"}
      `;
    if (!_confirm_(msg, title)) {
      return _toast_("↩️ Cancelled!", title);
    }

    try {
      this.createUser(name, email, role, password);
      msg = `✅ New user has been created!`;
    } catch (err) {
      msg = `🔴 ${err.message}`;
    }
    _alert_(msg, title);
  }
}

class Auth {
  constructor() {
    this.settings = _getSettings_(CONFIG.SETTINGS);
    this.ss = SpreadsheetApp.getActive();
  }

  validateToken(token) {
    return _verifyJwtToken_(token, this.settings.secretJwtToken);
  }

  createToken(data) {
    return _createJwtToken_(data, this.settings.secretJwtToken);
  }

  getUserByEmail(email) {
    email = email.trim().toLowerCase();
    return _getItemsFromSheet_(
      this.ss.getSheetByName(this.settings.sheetNameUsers),
      (v) => v.email.trim().toLowerCase() === email
    )[0];
  }

  getUserByName(name) {
    name = name.trim().toLowerCase();
    return _getItemsFromSheet_(
      this.ss.getSheetByName(this.settings.sheetNameUsers),
      (v) => v.name.trim().toLowerCase() === name
    )[0];
  }

  login({ email, password, token }) {
    if (email && password) {
      const user = this.getUserByEmail(email);
      if (!user) {
        throw new Error("User not found in the database.");
      }

      if (user.status.toLowerCase() !== "active") {
        throw new Error("User is deactivated. Contact the admin");
      }

      if (
        !_verifyHashedPassword_(
          password,
          user.password,
          this.settings.secretPasswordHash
        )
      ) {
        throw new Error("Invalid credentials!");
      }
      delete user.password;
      token = this.createToken(user);
      return {
        user,
        token,
      };
    }
    if (token) {
      const validToken = this.validateToken(token);
      if (!validToken) {
        return { user: null, token: null };
      }
      const tokenUser = this.getUserByEmail(validToken.email);
      if (!tokenUser || tokenUser.status.toLowerCase() !== "active") {
        return { user: null, token: null };
      }
      delete tokenUser.password;
      return {
        user: tokenUser,
        token,
      };
    }
    return {
      user: null,
      token: null,
    };
  }

  logout(payload) {
    const token = payload.token;
    if (!token) return;
    // TBD
  }

  validateLoginWithToken(token) {
    let loginInfo = this.login({ token });
    if (!loginInfo || !loginInfo.user) throw `Invalid login. Login again.`;
    return loginInfo;
  }
}

class PublicApp {
  constructor() {
    this.settings = _getSettings_(CONFIG.SETTINGS);
    this.ss = SpreadsheetApp.getActive();
    this.shProjects = this.ss.getSheetByName(this.settings.sheetNameProjects);
    this.shPayments = this.ss.getSheetByName(this.settings.sheetNamePayments);
    this.metadata;
    this.contractMetadata;
  }

  onOpen() {
    _createMenu_(this.settings.appName, [
      { caption: "+ New User", action: "addNewUser" },
      null,
      { caption: "Refresh Metadata Cache", action: "refreshMetadata" },
      {
        caption: "Set 30 min metadata autorefresh",
        action: "metadataAutorefresh",
      },
      null,
      { caption: "Re-authorize Freshbooks", action: "authorizeFB" },
      { caption: "Re-authorize Dropbox", action: "authorizeDropbox" },
    ]);
  }

  getDropdowns() {
    const data = {};
    const ws = this.ss.getSheetByName(this.settings.sheetNameDropdowns);
    const [headers, ...values] = ws.getDataRange().getValues();
    headers.forEach((header, i) => {
      const key = header.toString().toCamelCase();
      if (key) {
        data[key] = values.map((v) => v[i]).filter((v) => v);
      }
    });
    return data;
  }

  getAppData() {
    return {
      appName: this.settings.appName,
      urlLogo: this.settings.urlLogo,
      dropdowns: this.getDropdowns(),
      users: new User().getAllUsers(),
    };
  }

  doGet() {
    const template = HtmlService.createTemplateFromFile("index");
    // template.appData = JSON.stringify(this.getAppData());
    return template
      .evaluate()
      .setTitle(this.settings.appName)
      .addMetaTag("viewport", "width=device-width,initial-scale=1.0")
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  }

  getProperty(propName) {
    return PropertiesService.getScriptProperties().getProperty(propName);
  }

  setProperty(propName, value) {
    PropertiesService.getScriptProperties().setProperty(propName, value);
  }

  refreshMetadata() {
    let shMetadata = this.ss.getSheetByName("Metadata");
    let metaSheetData = _getItemsFromSheet_(shMetadata);
    this.metadata = {};
    metaSheetData.forEach(({ field, options }) => {
      this.metadata[field] = options.split("||");
    });

    this.setProperty(CONFIG.METADATA_PROP, JSON.stringify(this.metadata));
  }

  getMetadata() {
    if (!this.metadata) {
      this.refreshMetadata();
      this.metadata = JSON.parse(this.getProperty(CONFIG.METADATA_PROP) || {});
    }

    return this.metadata;
  }

  getContractMetadata() {
    let shScopes = this.ss.getSheetByName("Scopes");
    let shFavClient = this.ss.getSheetByName("Fav Clients");

    let scopes = _getItemsFromSheet_(shScopes);
    let favClients = _getItemsFromSheet_(shFavClient);

    return { scopes, favClients };
  }
}

class SecureApp extends PublicApp {
  constructor(token) {
    super();
    this.authApp = new Auth();
    this.user = this.authApp.validateLoginWithToken(token).user;
  }

  getProjects(filter) {
    if (!this.projects) {
      this.projects = _getParsedDataFromSheet_(this.shProjects, filter);
    }

    return this.projects;
  }

  getPayments(filter) {
    if (!this.payments) {
      this.payments = _getParsedDataFromSheet_(this.shPayments, filter);
    }

    return this.payments;
  }

  getNewProjectNumber() {
    let lock = LockService.getScriptLock();
    try {
      if (!lock.tryLock(60000)) {
        throw new Error("Could not acquire lock");
      }

      let projects = this.getProjects();
      let projectNumbers = projects
        .map((project) => parseFloat(project.projectNumber))
        .filter((num) => Number.isInteger(num));

      let maxProjectNumber =
        projectNumbers.length === 0 ? 100 : Math.max(...projectNumbers);

      let cachedProjectNumber = parseInt(
        this.getProperty(CONFIG.PROJECT_ID_PROP) || 0
      );

      if (cachedProjectNumber > maxProjectNumber) {
        this.setProperty(CONFIG.PROJECT_ID_PROP, cachedProjectNumber + 1);
        return cachedProjectNumber + 1;
      } else {
        this.setProperty(CONFIG.PROJECT_ID_PROP, maxProjectNumber + 1);
        return maxProjectNumber;
      }
    } finally {
      lock.releaseLock();
    }
  }

  getProjectById(id) {
    let projects = this.getProjects();
    let foundProject = projects.find((project) => project.id == id);
    if (!foundProject) throw `Project not found`;
    return foundProject;
  }

  getPaymentById(id) {
    let payments = this.getPayments();
    let foundPayment = payments.find((payment) => payment.id == id);
    if (!foundPayment) throw `Payment not found`;
    return foundPayment;
  }

  getSheetData() {
    let { name, role } = this.user;

    let projectData = this.getProjects(
      (project) => role == "Admin" || project.assignedTo.includes(name)
    );
    let paymentsData = this.getPayments(
      (payment) =>
        role == "Admin" || payment.assignee.toLowerCase() == name.toLowerCase()
    );
    return { projectData, paymentsData };
  }

  createProject(project) {
    if (!project.projectNumber) {
      project.projectNumber = this.getNewProjectNumber();
    }

    try {
      var dropboxFolderName = `Project ${project.projectNumber} - ${project.projectName}`;
      project.projectFilesFolder =
        createDropBoxFolderAndGetLink(dropboxFolderName);
    } catch (e) {
      console.log(e);
    }

    let lock = LockService.getScriptLock();
    try {
      if (!lock.tryLock(180000)) {
        throw new Error("Could not acquire lock");
      }

      this.shProjects.insertRowBefore(2);
      this.shProjects
        .getRange(2, 1, 1, 2)
        .setValues([[project.projectName, JSON.stringify(project)]]);
    } finally {
      lock.releaseLock();
    }
    return project;
  }

  updateProject(updatedValues) {
    let project = this.getProjectById(updatedValues.id);
    if (!project) throw "Project not found";

    let updatedProject = { ...project, ...updatedValues };
    this.shProjects
      .getRange(project._rowIndex, 2)
      .setValue(JSON.stringify(updatedProject));
  }

  archiveProjects(ids) {
    ids.forEach((id) => this.updateProject({ id, isArchived: true }));
  }

  unarchiveProjects(ids) {
    ids.forEach((id) => this.updateProject({ id, isArchived: false }));
  }

  createPayments(payments) {
    let outputData = payments.map((payment) => [
      payment.assignee,
      JSON.stringify(payment),
      payment.projectNumber,
    ]); //data should be an array

    let lock = LockService.getScriptLock();
    try {
      if (!lock.tryLock(180000)) {
        throw new Error("Could not acquire lock");
      }
      this.shPayments.insertRowsBefore(2, outputData.length);
      this.shPayments
        .getRange(2, 1, outputData.length, outputData[0].length)
        .setValues(outputData);
    } finally {
      lock.releaseLock();
    }
  }

  updatePayment(updatedValues) {
    let payment = this.getPaymentById(updatedValues.id);
    if (!payment) throw "Payment not found";

    let updatedPayment = { ...payment, ...updatedValues };
    this.shPayments
      .getRange(payment._rowIndex, 2)
      .setValue(JSON.stringify(updatedPayment));
  }

  deletePayment(id) {
    let payment = this.getPaymentById(id);
    if (!payment) return;

    this.shPayments.deleteRow(payment._rowIndex);
  }

  createExpense(payment) {
    let user = this.authApp.getUserByName(payment.assignee);
    if (!user) throw "User details not found";

    payment.expenseId = _createFBExpense_(payment, user);

    this.updatePayment(payment);
    return payment.expenseId;
  }

  createDropboxFolder(project) {
    try {
      let dropboxFolderName = `Project ${project.projectNumber} - ${project.projectName}`;
      var dropboxFolder = createDropBoxFolderAndGetLink(dropboxFolderName);
    } catch (e) {
      console.log(e);
    }

    project.projectFilesFolder = dropboxFolder;

    this.updateProject(project);

    return dropboxFolder;
  }
}

const doGet = (e) => new PublicApp().doGet(e);
const addNewUser = () => new User().addNewUser();
const login = ({ token, data }) => new Auth().login({ token, ...data });

const include = (filename) => _include_(filename);

const onOpen = () => new PublicApp().onOpen();
const getSheetData = ({ token }) => new SecureApp(token).getSheetData();
const updateProject = ({ token, data }) =>
  new SecureApp(token).updateProject(data);
const archiveProjects = ({ token, data }) =>
  new SecureApp(token).archiveProjects(data);
const unarchiveProjects = ({ token, data }) =>
  new SecureApp(token).unarchiveProjects(data);
const createProject = ({ token, data }) =>
  new SecureApp(token).createProject(data);
const createDropboxFolder = ({ token, data }) =>
  new SecureApp(token).createDropboxFolder(data);
const getNewProjectNumber = ({ token, data }) =>
  new SecureApp(token).getNewProjectNumber();

const createPayments = ({ token, data }) =>
  new SecureApp(token).createPayments(data);
const updatePayment = ({ token, data }) =>
  new SecureApp(token).updatePayment(data);
const deletePayment = ({ token, data }) =>
  new SecureApp(token).deletePayment(data);

//freshbooks functions
const createExpense = ({ token, data }) =>
  new SecureApp(token).createExpense(data);
const getFBClient = ({ data }) => _getFBClient_(data);
const createFBClient = ({ data }) => _createFBClient_(data);
const createFBInvoice = ({ data }) => _createFBInvoice_(data);
const createFBProject = ({ data }) => _createFBProject_(data);
const createContract = ({ data }) => _createContract_(data);

const refreshMetadata = () => new PublicApp().refreshMetadata();
const getMetadata = () => new PublicApp().getMetadata();
const getContractMetadata = () => new PublicApp().getContractMetadata();

const metadataAutorefresh = () => {
  let triggers = ScriptApp.getProjectTriggers();
  triggers.forEach((trigger) => {
    if (trigger.getHandlerFunction() == "refreshMetadata") {
      ScriptApp.deleteTrigger(trigger);
    }
  });

  ScriptApp.newTrigger("refreshMetadata").timeBased().everyMinutes(30).create();
};

const test = () => {
  let adminToken =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5MGE5NWNlLTM5MzMtNGI1Ny1hMTkxLTk2ZGMwNjdmOTg1MSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMDNUMTM6NTU6NTEuNzcyWiIsIm1vZGlmaWVkQXQiOiIyMDI0LTEwLTAzVDEzOjU1OjUxLjc3MloiLCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGNlZWRjaXZpbC5jb20iLCJyb2xlIjoiQWRtaW4iLCJzdGF0dXMiOiJBY3RpdmUiLCJfcm93SW5kZXgiOjN9.yyF0FGeVa4bOVauiHdJmwvN4gHi1YYwhi1y/ZQP3khg=";
  let empToken =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVjY2I1N2EwLWM0OTItNDlkOS04NmMwLTRmYzBjNTYyMGI3YSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMDFUMTQ6MzA6MDAuNjU4WiIsIm1vZGlmaWVkQXQiOiIyMDI0LTEwLTAxVDE0OjMwOjAwLjY1OFoiLCJuYW1lIjoiQXJuZWwiLCJlbWFpbCI6ImlhbXBhcnJ0aEBnbWFpbC5jb20iLCJyb2xlIjoiRW1wbG95ZWUiLCJzdGF0dXMiOiJBY3RpdmUiLCJfcm93SW5kZXgiOjJ9.fUo9EAvFMb+BBYJPKEgmSVZWlGnXej3Mr2FRRjbvxiU=";

  let payload = {"data":{"notes":"","revisionCost":"3","dateModified":"2024-10-09T21:27:20.672Z","revisionNeeded":false,"_rowIndex":814,"revisionPaid":false,"dateCreated":"2024-10-09T21:27:20.672Z","paid":false,"assignee":"Arnel","id":"ab72c74a-73ed-4858-a27f-303a3489a219","projectId":"a102d129-e74e-40b3-a30e-6b32a3f77998","totalCost":4,"actualCost":"1","datePaid":null,"datePaid2":null},"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5MGE5NWNlLTM5MzMtNGI1Ny1hMTkxLTk2ZGMwNjdmOTg1MSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMDNUMTM6NTU6NTEuNzcyWiIsIm1vZGlmaWVkQXQiOiIyMDI0LTEwLTAzVDEzOjU1OjUxLjc3MloiLCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGNlZWRjaXZpbC5jb20iLCJyb2xlIjoiQWRtaW4iLCJzdGF0dXMiOiJBY3RpdmUiLCJtZXJjaGFudE5hbWUiOiJBZG1pbiIsImNhdGVnb3J5TmFtZSI6IkRyYWZ0ZXIgLSBDb250cmFjdG9yIiwiX3Jvd0luZGV4IjozfQ==.q3sodyDSjuplKUYL6ZHy6FgnPS0rAMfgeeUHXFaf2Vg="}

  console.log(createExpense(payload));

  // console.log(new SecureApp(payload.token).createExpense(payload.data));

  // payload = { "data": { "projectNumber": "", "invoiceNumber": "90000", "projectName": "FL - Container Home - I-beams", "salesMan": "Jerry", "description": "asdf", "overallProjectStatus": "HOLD", "state": "Alabama", "priority": "Urgent", "projectFilesFolder": "asdf", "projectNotes": "asfd", "clientProjectNameAddress": "asfd", "assignedTo": ["Admin"], "contractLink": "asf", "depositPaid": false, "estimatedBudget": "asf", "actualCost": "", "initialProjectStatus": "Submitted for Permit", "drafterNeeded": false, "drafterTaskedTo": "", "draftingStatus": "", "draftingDropboxLink": "", "draftingEstimatedDeliveryTime": "", "engineeringNeeded": false, "engineerTaskedTo": "", "engineeringStatus": "", "engineeringDropboxLink": "", "engineeringEstimatedDeliveryTime": "", "mepNeeded": false, "mepTaskedTo": "", "mepStatus": "", "mepDropboxLink": "", "mepEstimatedDeliveryTime": "", "civilNeeded": false, "civilEngineeringTaskedTo": "", "civilEngineeringStatus": "", "civilDropboxLink": "", "civilEstimatedDeliveryTime": "", "jobType": "", "isArchived": false, "id": "214e4dbf-724c-40b4-ba65-c2306f4497aa", "dateCreated": "2024-10-07T06:07:21.555Z", "dateModified": "2024-10-07T06:07:21.555Z", "createdBy": "Admin", "modifiedBy": "Admin" }, "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5MGE5NWNlLTM5MzMtNGI1Ny1hMTkxLTk2ZGMwNjdmOTg1MSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMDNUMTM6NTU6NTEuNzcyWiIsIm1vZGlmaWVkQXQiOiIyMDI0LTEwLTAzVDEzOjU1OjUxLjc3MloiLCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGNlZWRjaXZpbC5jb20iLCJyb2xlIjoiQWRtaW4iLCJzdGF0dXMiOiJBY3RpdmUiLCJfcm93SW5kZXgiOjN9.yyF0FGeVa4bOVauiHdJmwvN4gHi1YYwhi1y/ZQP3khg=" }

  // console.log(new SecureApp(payload.token).createProject(payload.data))
  // new Auth().login({ token: data.token });
};

const testLogin = () => {
  console.log(
    new Auth().login({ email: "iamparrth@gmail.com", password: "1234" })
  );
};
