const CONFIG = {
  SETTINGS: "⚙️Settings",
  DATE_PREFIX: "D",
};

class User {
  constructor() {
    this.settings = _getSettings_(CONFIG.SETTINGS);
    this.ss = SpreadsheetApp.getActive();
    this.ws = this.ss.getSheetByName(this.settings.sheetNameUsers);
  }

  getAllUsers() {
    return _getItemsFromSheet_(
      this.ss.getSheetByName(this.settings.sheetNameUsers)
    );
  }

  emailUser(values, password) {
    const [name, email, role] = values.slice(3);
    const subject = `You've been invited to ${this.settings.appName}`;
    const htmlBody = `
			<p>Welcome ${name},</p>
			<p>You've been invited to user our ${this.settings.appName}!</p>
			<p>
				Role: ${role}<br/>
				Email: ${email}<br/>
				Password: ${password}<br/>
				App: ${this.settings.urlApp}
			</p>

			<p style="color: #64596F;">
				<small>
					${this.settings.appName}<br>
					<a href="https://www.ceedcivil.com/" target="_blank" style="color: #A482B6">www.ceedcivil.com</a>
				</small>
			</p>
		`;
    const options = {
      name: this.settings.appName,
      htmlBody,
    };
    GmailApp.sendEmail(email, subject, "", options);
  }

  createUser(name, email, role, password) {
    password = password || _generatePassword_(6);
    const id = Utilities.getUuid();
    const createdAt = new Date().toISOString();
    const hashedPassword = _hashPassword_(
      password,
      this.settings.secretPasswordHash
    );
    const values = [
      id,
      createdAt,
      createdAt,
      name,
      email,
      role,
      "Active",
      hashedPassword,
    ];
    this.ws.appendRow(values);
    this.emailUser(values, password);
  }

  addNewUser() {
    const title = "+ New User";
    const ui = _getUi_();

    let msg = `What's the name of the new user (required)?`;
    const nameInput = _prompt_(msg, title);
    if (nameInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    const name = nameInput.getResponseText().trim();
    if (!name) {
      msg = "🔴 The name of the user is required!";
      return _alert_(msg, title);
    }

    msg = `What's the role of the new user (required)?

      Option 1: Admin
      Option 2: Employee (default)
      `;
    const roleInput = _prompt_(msg, title);
    if (roleInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    let role = roleInput.getResponseText().trim().toLowerCase();
    if (role == "1" || role === "admin") {
      role = "Admin";
    } else {
      role = "Employee";
    }

    msg = `What's the email address of the new user (required)?`;
    const emailInput = _prompt_(msg, title);
    if (emailInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    const email = emailInput.getResponseText().trim();
    if (!email) {
      msg = "🔴 The name of the user is required!";
      return _alert_(msg, title);
    } else if (email.indexOf("@") <= 0) {
      msg = "🔴 Invalid email address!";
      return _alert_(msg, title);
    }

    msg = `What's the password of the new user (optional)?`;
    const passwordInput = _prompt_(msg, title);
    if (passwordInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    const password = passwordInput.getResponseText().trim();

    msg = `Are you sure to add this new user?

      Name: ${name}
      Email: ${email}
      Role: ${role}
      Password: ${password || "will be generated by the script"}
      `;
    if (!_confirm_(msg, title)) {
      return _toast_("↩️ Cancelled!", title);
    }

    try {
      this.createUser(name, email, role, password);
      msg = `✅ New user has been created!`;
    } catch (err) {
      msg = `🔴 ${err.message}`;
    }
    _alert_(msg, title);
  }
}

class Auth {
  constructor() {
    this.settings = _getSettings_(CONFIG.SETTINGS);
    this.ss = SpreadsheetApp.getActive();
  }

  validateToken(token) {
    return _verifyJwtToken_(token, this.settings.secretJwtToken);
  }

  createToken(data) {
    return _createJwtToken_(data, this.settings.secretJwtToken);
  }

  getUserByEmail(email) {
    email = email.trim().toLowerCase();
    return _getItemsFromSheet_(
      this.ss.getSheetByName(this.settings.sheetNameUsers),
      (v) => v.email.trim().toLowerCase() === email
    )[0];
  }

  login({ email, password, token }) {
    if (email && password) {
      const user = this.getUserByEmail(email);
      if (!user) {
        throw new Error("User not found in the database.");
      }
      if (
        !_verifyHashedPassword_(
          password,
          user.password,
          this.settings.secretPasswordHash
        )
      ) {
        throw new Error("Invalid credentials!");
      }
      delete user.password;
      token = this.createToken(user);
      return {
        user,
        token,
      };
    }
    if (token) {
      const validToken = this.validateToken(token);
      if (!validToken) {
        return { user: null, token: null };
      }
      const tokenUser = this.getUserByEmail(validToken.email);
      if (!tokenUser || tokenUser.status.toLowerCase() !== "active") {
        return { user: null, token: null };
      }
      delete tokenUser.password;
      return {
        user: tokenUser,
        token,
      };
    }
    return {
      user: null,
      token: null,
    };
  }

  logout(payload) {
    const token = payload.token;
    if (!token) return;
    // TBD
  }

  validateLoginWithToken(token) {
    let loginInfo = this.login({ token });
    if (!loginInfo || !loginInfo.user) throw `Invalid login. Login again.`;
    return loginInfo
  }
}

class PublicApp {
  constructor() {
    this.settings = _getSettings_(CONFIG.SETTINGS);
    this.ss = SpreadsheetApp.getActive();
    this.shProjects = this.ss.getSheetByName(this.settings.sheetNameProjects);
    this.shPayments = this.ss.getSheetByName(this.settings.sheetNamePayments);
  }

  onOpen() {
    _createMenu_(this.settings.appName, [
      { caption: "+ New User", action: "addNewUser" },
    ]);
  }

  getDropdowns() {
    const data = {};
    const ws = this.ss.getSheetByName(this.settings.sheetNameDropdowns);
    const [headers, ...values] = ws.getDataRange().getValues();
    headers.forEach((header, i) => {
      const key = header.toString().toCamelCase();
      if (key) {
        data[key] = values.map((v) => v[i]).filter((v) => v);
      }
    });
    return data;
  }

  getAppData() {
    return {
      appName: this.settings.appName,
      urlLogo: this.settings.urlLogo,
      dropdowns: this.getDropdowns(),
      users: new User().getAllUsers(),
    };
  }

  doGet() {
    const template = HtmlService.createTemplateFromFile("index.html");
    // template.appData = JSON.stringify(this.getAppData());
    return template
      .evaluate()
      .setTitle(this.settings.appName)
      .addMetaTag("viewport", "width=device-width,initial-scale=1.0")
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  }
}

class SecureApp extends PublicApp {
  constructor(token) {
    super();
    this.authApp = new Auth();
    this.user = this.authApp.validateLoginWithToken(token).user;
  }

  getProjects(filter) {
    return _getParsedDataFromSheet_(this.shProjects, filter)
  }

  getPayments(filter) {
    return _getParsedDataFromSheet_(this.shPayments, filter)
  }

  getProjectById(id) {
    let projects = this.getProjects()
    let foundProject = projects.find(project => project.id == id)
    if (!foundProject) throw `Project not found`
    return foundProject
  }

  getSheetData() {
    let { name, role } = this.user;

    let projectData = this.getProjects(project => role == 'Admin' || project.assignedTo.includes(name));
    let paymentsData = this.getPayments(payment => role == 'Admin' || payment.assignee.toLowerCase() == name.toLowerCase());
    return { projectData, paymentsData };
  }

  updateProject({ data }) {
    let project = this.getProjectById(data.id);
    if (!project) throw 'Project not found';

    let updatedProject = { ...project, ...data };
    this.shProjects.getRange(project._rowIndex, 2).setValue(JSON.stringify(updatedProject));
  }
}


const doGet = (e) => new PublicApp().doGet(e);
const addNewUser = () => new User().addNewUser();
const login = (payload) => new Auth().login(payload.data);

const include = (filename) => _include_(filename);

const onOpen = () => new PublicApp().onOpen();
const getSheetData = (payload) => new SecureApp(payload.token).getSheetData(payload);
const updateProject = (payload) => new SecureApp(payload.token).updateProject(payload)

const test = () => {
  let adminToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5MGE5NWNlLTM5MzMtNGI1Ny1hMTkxLTk2ZGMwNjdmOTg1MSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMDNUMTM6NTU6NTEuNzcyWiIsIm1vZGlmaWVkQXQiOiIyMDI0LTEwLTAzVDEzOjU1OjUxLjc3MloiLCJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGNlZWRjaXZpbC5jb20iLCJyb2xlIjoiQWRtaW4iLCJzdGF0dXMiOiJBY3RpdmUiLCJfcm93SW5kZXgiOjN9.yyF0FGeVa4bOVauiHdJmwvN4gHi1YYwhi1y/ZQP3khg="
  let empToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVjY2I1N2EwLWM0OTItNDlkOS04NmMwLTRmYzBjNTYyMGI3YSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMDFUMTQ6MzA6MDAuNjU4WiIsIm1vZGlmaWVkQXQiOiIyMDI0LTEwLTAxVDE0OjMwOjAwLjY1OFoiLCJuYW1lIjoiQXJuZWwiLCJlbWFpbCI6ImlhbXBhcnJ0aEBnbWFpbC5jb20iLCJyb2xlIjoiRW1wbG95ZWUiLCJzdGF0dXMiOiJBY3RpdmUiLCJfcm93SW5kZXgiOjJ9.fUo9EAvFMb+BBYJPKEgmSVZWlGnXej3Mr2FRRjbvxiU='
  let payload = { "data": { "id": "043f14e2-6181-4ae2-8558-93e01cd470f3", "assignedTo": ["Admin", "Arnel", "Civil Engineer"] }, "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVjY2I1N2EwLWM0OTItNDlkOS04NmMwLTRmYzBjNTYyMGI3YSIsImNyZWF0ZWRBdCI6IjIwMjQtMTAtMDFUMTQ6MzA6MDAuNjU4WiIsIm1vZGlmaWVkQXQiOiIyMDI0LTEwLTAxVDE0OjMwOjAwLjY1OFoiLCJuYW1lIjoiQXJuZWwiLCJlbWFpbCI6ImlhbXBhcnJ0aEBnbWFpbC5jb20iLCJyb2xlIjoiRW1wbG95ZWUiLCJzdGF0dXMiOiJBY3RpdmUiLCJfcm93SW5kZXgiOjJ9.fUo9EAvFMb+BBYJPKEgmSVZWlGnXej3Mr2FRRjbvxiU=" }
  console.log(new SecureApp(payload.token).updateProject(payload))
  // new Auth().login({ token: data.token });
};

const testLogin = () => {
  console.log(new Auth().login({ email: 'iamparrth@gmail.com', password: '1234' }))
}
