export const topBarHeight = 64;
export const sideNavWidth = 260;
export const navbarHeight = 60;
export const sidenavCompactWidth = 80;
export const containedLayoutWidth = 1200;
export const INITIAL_FORM = {
  sameAsClient: false,
  fbInvoiceId: "",
  fbClientId: "",
  fbProjectId: "",
  date: "",
  clientName: "",
  clientStreet: "",
  clientCity: "",
  clientState: "",
  clientZip: "",
  clientCompany: "",
  clientAddress: "",
  clientEmail: "",
  clientPhone: "",
  siteAddress: "",
  siteCity: "",
  siteZip: "",
  siteState: "",
  retainerRemaining: "",
  salesMan: "",
  deliveryDuration: "",
  gap: 0,
  siteStreet: "",
  remainingBalance: "",
  scopes: [],
  favClients: "",
  isUpworkJob: false,
  retainerDeposit: "",
  projectNumber: "",
  deliverableFromClient: "",
  projectName: "",
  totalCost: "",
  ratePerHour: 225,
  documentUrl: "",
  sendClientEmail: true,
  drafterFolderNeeded: true,
  enggFolderNeeded: true,
  mepFolderNeeded: true,
  civilFolderNeeded: true,
  draftingTaskedTo: [],
  engineeringTaskedTo: [],
  mepTaskedTo: [],
  civilTaskedTo: []
};

export const DEV_PREFILL_FORM = {
  sameAsClient: true,
  fbInvoiceId: "0001672",
  date: "2024-09-14",
  clientName: "test test",
  clientStreet: "Test Test",
  clientState: "California",
  clientCompany: "Test test",
  clientZip: "95112",
  clientCity: "test",
  clientEmail: "test@test.com",
  clientAddress: "Test Test",
  clientPhone: "(000)000-0000",
  siteAddress: "Test Test",
  siteCity: "San Jose",
  siteState: "California",
  siteZip: "95119",
  retainerRemaining: 5600,
  checkBox: "on",
  salesMan: "Ryan",
  deliveryDuration: "1 - 2 Weeks",
  siteStreet: "6373 San Igancio",
  favClients: "",
  gap: 0,
  remainingBalance: 0,
  isUpworkJob: false,
  retainerDeposit: 9,
  projectNumber: "999",
  fbProjectId: "12518535",
  fbClientId: "",
  deliverableFromClient: "CAD and PDF files",
  projectName: "Test",
  totalCost: 9,
  ratePerHour: 200,
  documentUrl: "",
  scopes: [
    {
      detail:
        "Preparation of design computations and construction drawings for building plans. Soil assumed at 1500 PSF unless soil report provided. All loads as shown. Single use for address as shown",
      description: "Building Plan Calculations Package",
      rate: 5
    },
    {
      rate: 2,
      description: "Calculations Report",
      detail: "Calculations report for the openings in the ceiling."
    },
    {
      description: "Engineering Review, Stamp and Seal P.E.",
      detail:
        "Scope of work, reviewed, stamped, and sealed by state licensed P.E. CA",
      rate: 2
    }
  ],
  sendClientEmail: true,
  drafterFolderNeeded: true,
  enggFolderNeeded: true,
  mepFolderNeeded: true,
  civilFolderNeeded: true,
  draftingTaskedTo: [],
  engineeringTaskedTo: [],
  mepTaskedTo: [],
  civilTaskedTo: []
};

export const BLANK_PROJECT = {
  id: null,
  projectNumber: "",
  invoiceNumber: null,
  projectName: "",
  salesMan: "",
  description: "",
  overallProjectStatus: "",
  state: "",
  priority: "",
  projectFilesFolder: "",
  projectNotes: "",
  clientProjectNameAddress: "",
  assignedTo: [],
  contractLink: "",
  depositPaid: false,
  estimatedBudget: "",
  actualCost: "",
  initialProjectStatus: "",
  draftingNeeded: false,
  draftingTaskedTo: [],
  draftingStatus: "",
  draftingEstimate: "",
  draftingDropboxLink: "",
  draftingEstimatedDeliveryTime: "",
  engineeringNeeded: false,
  engineeringTaskedTo: [],
  engineeringStatus: "",
  engineeringEstimate: "",
  engineeringDropboxLink: "",
  engineeringEstimatedDeliveryTime: "",
  mepNeeded: false,
  mepTaskedTo: [],
  mepStatus: "",
  mepEstimate: "",
  mepDropboxLink: "",
  mepEstimatedDeliveryTime: "",
  civilNeeded: false,
  civilTaskedTo: [],
  civilStatus: "",
  civilEstimate: "",
  civilDropboxLink: "",
  civilEstimatedDeliveryTime: "",
  jobType: "",
  isArchived: false,
  expenses: [],
  folderOptions: {
    sendClientEmail: true,
    drafter: true,
    engg: true,
    mep: true,
    civil: true
  },
  chats: []
};

export const BLANK_PAYMENT = {
  id: "",
  assignee: "",
  projectNumber: "",
  projectName: "",
  salesMan: "",
  overallProjectStatus: "",
  estimatedBudget: "",
  actualCost: "",
  paid: false,
  datePaid: "",
  revisionNeeded: false,
  datePaid2: "",
  revisionCost: "",
  revisionsPaid: false,
  notes: "",
  totalCost: "",
  expenseId: ""
};
