//changes on 23th Jan to fix number system in forms
const CONFIG = {
  SETTINGS: "⚙️Settings",
  DATE_PREFIX: "D",
  PROJECT_ID_PROP: "LastProjectId",
  METADATA_PROP: "Dropdowns",
  CONTRACT_META_PROP: "ContractMetaData",
  CONTRACT_ALTERNATE_COLORS: {
    color1: "#FFFFFF",
    color2: "#F3EFEF",
  },
  version: 2
};

class User {
  constructor() {
    this.settings = _getSettings_(CONFIG.SETTINGS);
    this.ss = SpreadsheetApp.getActive();
    this.ws = this.ss.getSheetByName(this.settings.sheetNameUsers);
  }

  getAllUsers() {
    return _getItemsFromSheet_(
      this.ss.getSheetByName(this.settings.sheetNameUsers)
    );
  }

  emailUser(values, password) {
    const [name, email, role] = values.slice(3);
    const subject = `You've been invited to ${this.settings.appName}`;
    const htmlBody = `
			<p>Welcome ${name},</p>
			<p>You've been invited to use our ${this.settings.appName}!</p>
			<p>
				Email: ${email}<br/>
				Password: ${password}<br/>
				App: ${this.settings.urlApp}
			</p>

			<p style="color: #64596F;">
				<small>
					${this.settings.appName}<br>
					<a href="https://www.ceedcivil.com/" target="_blank" style="color: #A482B6">www.ceedcivil.com</a>
				</small>
			</p>
		`;
    const options = {
      name: this.settings.appName,
      htmlBody,
      cc: 'ceedcivil@gmail.com'
    };
    GmailApp.sendEmail(email, subject, "", options);
  }

  createUser(name, email, role, password) {
    password = password || _generatePassword_(6);
    const id = Utilities.getUuid();
    const createdAt = new Date().toISOString();
    const hashedPassword = _hashPassword_(
      password,
      this.settings.secretPasswordHash
    );
    const values = [
      id,
      createdAt,
      createdAt,
      name,
      email,
      role,
      "Active",
      hashedPassword,
    ];
    this.ws.appendRow(values);

    this.emailUser(values, password);
    
    //share the root folder
    const rootFolderUrl = this.settings.projectsRootFolder
    const rootFolder = DriveApp.getFolderById(_getIdFromUrl_(rootFolderUrl))
    rootFolder.addEditor(email)
  }

  addNewUser() {
    const title = "+ New User";
    const ui = _getUi_();

    let msg = `What's the name of the new user (required)?`;
    const nameInput = _prompt_(msg, title);
    if (nameInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    const name = nameInput.getResponseText().trim();
    if (!name) {
      msg = "🔴 The name of the user is required!";
      return _alert_(msg, title);
    }

    msg = `What's the role of the new user (required)?

      Option 1: Admin
      Option 2: Employee (default)
      `;
    const roleInput = _prompt_(msg, title);
    if (roleInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    let role = roleInput.getResponseText().trim().toLowerCase();
    if (role == "1" || role === "admin") {
      role = "Admin";
    } else {
      role = "Employee";
    }

    msg = `What's the email address of the new user (required)?`;
    const emailInput = _prompt_(msg, title);
    if (emailInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    const email = emailInput.getResponseText().trim();
    if (!email) {
      msg = "🔴 The name of the user is required!";
      return _alert_(msg, title);
    } else if (email.indexOf("@") <= 0) {
      msg = "🔴 Invalid email address!";
      return _alert_(msg, title);
    }

    msg = `What's the password of the new user (optional)?`;
    const passwordInput = _prompt_(msg, title);
    if (passwordInput.getSelectedButton() !== ui.Button.OK) {
      return _toast_("↩️ Cancelled!", title);
    }
    const password = passwordInput.getResponseText().trim();

    msg = `Are you sure to add this new user?

      Name: ${name}
      Email: ${email}
      Role: ${role}
      Password: ${password || "will be generated by the script"}
      `;
    if (!_confirm_(msg, title)) {
      return _toast_("↩️ Cancelled!", title);
    }

    try {
      this.createUser(name, email, role, password);
      msg = `✅ New user has been created!`;
    } catch (err) {
      msg = `🔴 ${err.message}`;
    }
    _alert_(msg, title);
  }

  resendInvitation() {
    const title = "Resend Invitation Email";

    // Get selected range
    const range = this.ss.getActiveRange();
    if (!range) {
      throw new Error('Please select a user row first');
    }

    const row = range.getRow();
    const numRows = range.getNumRows();

    // Validate selection
    if (numRows !== 1) {
      throw new Error('Please select only one row');
    }

    // Check if selection is in the data range (not header)
    const headerRows = 1; // Assuming 1 header row
    if (row <= headerRows) {
      throw new Error('Please select a user row, not the header');
    }

    try {
      this.resendInvitationEmail(row);
      _toast_("✅ Invitation email has been resent successfully!", title);
    } catch (err) {
      if (err.message === 'Operation cancelled by user') {
        _toast_("↩️ Cancelled!", title);
      } else {
        _alert_(`🔴 ${err.message}`, title);
      }
    }
  }
  
  resendInvitationEmail(row) {
    const title = "Resend Invitation Email";

    // Get all the values from the selected row
    const rowValues = this.ws.getRange(row, 1, 1, this.ws.getLastColumn()).getValues()[0];
    const [id, createdAt, updatedAt, name, email, role, status, hashedPassword] = rowValues;

    if (status !== 'Active') {
      throw new Error('Cannot resend invitation to inactive user');
    }

    // Confirm resend
    const msg = `Are you sure you want to resend invitation email to:\n\nName: ${name}\nEmail: ${email}\nRole: ${role}`;
    if (!_confirm_(msg, title)) {
      throw new Error('Operation cancelled by user');
    }

    let password = '';
    let newHashedPassword = hashedPassword;

    password = _generatePassword_(6);
    newHashedPassword = _hashPassword_(password, this.settings.secretPasswordHash);

    this.ws.getRange(row, 8).setValue(newHashedPassword); // Password column
    this.ws.getRange(row, 3).setValue(new Date().toISOString()); // UpdatedAt column

    const values = [id, createdAt, new Date().toISOString(), name, email, role];

    try {
      this.emailUser(values, password || 'Use your existing password');
      return true;
    } catch (error) {
      throw new Error(`Failed to send email: ${error.message}`);
    }
  }
}

class Auth {
  constructor() {
    this.settings = _getSettings_(CONFIG.SETTINGS);
    this.ss = SpreadsheetApp.getActive();
  }

  validateToken(token) {
    return _verifyJwtToken_(token, this.settings.secretJwtToken);
  }

  createToken(data) {
    return _createJwtToken_(data, this.settings.secretJwtToken);
  }

  getUserByEmail(email) {
    email = email.trim().toLowerCase();
    return _getItemsFromSheet_(
      this.ss.getSheetByName(this.settings.sheetNameUsers),
      (v) => v.email.trim().toLowerCase() === email
    )[0];
  }

  getUserByName(name) {
    name = name.trim().toLowerCase();
    return _getItemsFromSheet_(
      this.ss.getSheetByName(this.settings.sheetNameUsers),
      (v) => v.name.trim().toLowerCase() === name
    )[0];
  }

  login({ email, password, token }) {
    console.log('Loggin in with ', {email, password, token})
    if (email && password) {
      const user = this.getUserByEmail(email);
      if (!user) {
        throw new Error("User not found in the database.");
      }

      if (user.status.toLowerCase() !== "active") {
        throw new Error("User is deactivated. Contact the admin");
      }

      if (
        !_verifyHashedPassword_(
          password,
          user.password,
          this.settings.secretPasswordHash
        )
      ) {
        throw new Error("Invalid credentials!");
      }
      delete user.password;
      token = this.createToken(user);
      return {
        user,
        token,
      };
    }
    if (token) {
      const validToken = this.validateToken(token);
      if (!validToken) {
        return { user: null, token: null };
      }
      const tokenUser = this.getUserByEmail(validToken.email);
      if (!tokenUser || tokenUser.status.toLowerCase() !== "active") {
        return { user: null, token: null };
      }
      delete tokenUser.password;
      return {
        user: tokenUser,
        token,
      };
    }
    return {
      user: null,
      token: null,
    };
  }

  logout(payload) {
    const token = payload.token;
    if (!token) return;
    // TBD
  }

  validateLoginWithToken(token) {
    let loginInfo = this.login({ token });
    if (!loginInfo || !loginInfo.user) throw `Invalid login. Login again.`;
    return loginInfo;
  }
}

class PublicApp {
  constructor() {
    this.settings = _getSettings_(CONFIG.SETTINGS);
    this.ss = SpreadsheetApp.getActive();
    this.shProjects = this.ss.getSheetByName(this.settings.sheetNameProjects);
    this.shPayments = this.ss.getSheetByName(this.settings.sheetNamePayments);
    this.metadata;
    this.contractMetadata;
  }

  onOpen() {
    _createMenu_(this.settings.appName, [
      { caption: "+ New User", action: "addNewUser" },
      { caption: "Resend Invitation", action: "resendInvitation" },
      null,
      { caption: "Re-authorize Freshbooks", action: "authorizeFB" },
      { caption: "Re-authorize Dropbox", action: "authorizeDropbox" },
      null,
      { caption: "Refresh Metadata Cache", action: "refreshMetadata" },
      {
        caption: "Set 30 min metadata autorefresh",
        action: "metadataAutorefresh",
      },
    ]);
  }

  getDropdowns() {
    const data = {};
    const ws = this.ss.getSheetByName(this.settings.sheetNameDropdowns);
    const [headers, ...values] = ws.getDataRange().getValues();
    headers.forEach((header, i) => {
      const key = header.toString().toCamelCase();
      if (key) {
        data[key] = values.map((v) => v[i]).filter((v) => v);
      }
    });
    return data;
  }

  getAppData() {
    let metadata = this.getMetadata()

    return {
      ...metadata,
      appName: this.settings.appName,
      urlLogo: this.settings.urlLogo,
      contractExportFolder: this.settings.contractExportFolder,
      contractTemplate: this.settings.contractTemplate
    };
  }

  doGet() {
    const template = HtmlService.createTemplateFromFile("index");
    // template.contractExportFolder = this.settings.contractExportFolder
    // template.contractTemplate = this.settings.contractTemplate
    template.appData = JSON.stringify(this.getAppData());
    return template
      .evaluate()
      .setTitle(this.settings.appName)
      .addMetaTag("viewport", "width=device-width,initial-scale=1.0")
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  }

  getProperty(propName) {
    return PropertiesService.getScriptProperties().getProperty(propName);
  }

  setProperty(propName, value) {
    PropertiesService.getScriptProperties().setProperty(propName, value);
  }

  refreshMetadataOld() {
    let shMetadata = this.ss.getSheetByName("Metadata");
    let metaSheetData = _getItemsFromSheet_(shMetadata);
    this.metadata = {};
    metaSheetData.forEach(({ field, options }) => {
      this.metadata[field] = options.split("||");
    });

    this.setProperty(CONFIG.METADATA_PROP, JSON.stringify(this.metadata));
  }

  refreshMetadata() {
    let shMetadata = this.ss.getSheetByName("Dropdowns");
    let [headers, ...values] = shMetadata.getDataRange().getValues()

    let keys = _createKeys_(headers)

    this.metadata = {};
    keys.forEach((header, index) => {
      this.metadata[header] = values.filter(valueRow => !!valueRow[index]).map(valueRow => valueRow[index])
    })

    this.setProperty(CONFIG.METADATA_PROP, JSON.stringify(this.metadata));
  }

  getMetadata() {
    this.metadata = JSON.parse(this.getProperty(CONFIG.METADATA_PROP) | '{}')

    if (!this.metadata) this.refreshMetadata();

    return this.metadata;
  }

  getContractMetadata() {
    let shScopes = this.ss.getSheetByName("Scopes");
    let shFavClient = this.ss.getSheetByName("Fav Clients");

    let scopes = _getItemsFromSheet_(shScopes);
    let favClients = _getItemsFromSheet_(shFavClient);

    return { scopes, favClients };
  }
}

class SecureApp extends PublicApp {
  constructor(token) {
    super();
    this.authApp = new Auth();
    this.user = this.authApp.validateLoginWithToken(token).user;
  }

  getProjects(filter) {
    if (!this.projects) {
      this.projects = _getParsedDataFromSheet_(this.shProjects, filter);
    }

    return this.projects;
  }

  getPayments(filter) {
    if (!this.payments) {
      this.payments = _getParsedDataFromSheet_(this.shPayments, filter);
    }

    return this.payments;
  }

  getNewProjectNumber() {
    let lock = LockService.getScriptLock();
    try {
      if (!lock.tryLock(60000)) {
        throw new Error("Could not acquire lock");
      }

      let projects = this.getProjects();
      let projectNumbers = projects
        .map((project) => parseFloat(project.projectNumber))
        .filter((num) => Number.isInteger(num));

      let maxProjectNumber =
        projectNumbers.length === 0 ? 100 : Math.max(...projectNumbers);

      let cachedProjectNumber = parseInt(
        this.getProperty(CONFIG.PROJECT_ID_PROP) || 0
      );

      if (cachedProjectNumber > maxProjectNumber) {
        this.setProperty(CONFIG.PROJECT_ID_PROP, cachedProjectNumber + 1);
        return cachedProjectNumber + 1;
      } else {
        this.setProperty(CONFIG.PROJECT_ID_PROP, maxProjectNumber + 1);
        return maxProjectNumber + 1;
      }
    } finally {
      lock.releaseLock();
    }
  }

  getProjectById(id) {
    let projects = this.getProjects();
    let foundProject = projects.find((project) => project.id == id);
    if (!foundProject) throw `Project not found`;
    return foundProject;
  }

  getPaymentById(id) {
    let payments = this.getPayments();
    let foundPayment = payments.find((payment) => payment.id == id);
    if (!foundPayment) throw `Payment not found`;
    return foundPayment;
  }

  getSheetData() {
    let { name, role } = this.user;

    let projects = this.getProjects(
      (project) => role == "Admin" || project.assignedTo.includes(name)
    );
    let payments = this.getPayments(
      (payment) =>
        role == "Admin" || payment.assignee.toLowerCase() == name.toLowerCase()
    );
    return { projects, payments };
  }

  createProject(project) {
    console.log(`Creating project `,project)

    if (!project.projectNumber) {
      project.projectNumber = this.getNewProjectNumber();
      console.log(`New project number ${project.projectNumber} generated!`)
    }

    try {
      // var dropboxFolderName = `Project ${project.projectNumber} - ${project.projectName}`;
      const folderUrls = this.createDriveFolderStructure(project)
      
      project.projectFilesFolder = folderUrls.root
      project.draftingDropboxLink = folderUrls.arch
      project.engineeringDropboxLink = folderUrls.structural
      project.mepDropboxLink = folderUrls.mep
      project.civilDropboxLink = folderUrls.civil
    } catch (e) {
      console.log(`Error while creating folder`, e);
    }

    let lock = LockService.getScriptLock();
    try {
      if (!lock.tryLock(180000)) {
        throw new Error("Could not acquire lock");
      }
      this.shProjects.insertRowBefore(2);
      this.shProjects
        .getRange(2, 1, 1, 2)
        .setValues([[project.projectName, JSON.stringify({ ...project, dateCreated: new Date().toISOString(), dateModified: new Date().toISOString(), modifiedBy: this.user?.name, createdBy: this.user?.name })]]);
    }finally{
      lock.releaseLock()
    }
    return project;
  }

  updateProject(updatedValues) {
    console.log('Updating the project ', updatedValues)
    let project = this.getProjectById(updatedValues.id);
    if (!project) throw "Project not found";

    let updatedProject = { ...project, ...updatedValues, dateModified: new Date().toISOString(), modifiedBy: this.user?.name };

    if (project.overallProjectStatus !== 'Pending S&S' && updatedValues.overallProjectStatus == 'Pending S&S') {
      _sendEmail_(this.settings['statusChangedToPendingS&s'], this.settings['sendS&sEmailTo'], updatedProject)
    }

    let lock = LockService.getScriptLock();
    try {
      if (!lock.tryLock(180000)) {
        throw new Error("Could not acquire lock");
      }
      this.shProjects
        .getRange(project._rowIndex, 2)
        .setValue(JSON.stringify(updatedProject));
    }finally{
      lock.releaseLock()
    }
  }

  archiveProjects(ids) {
    ids.forEach((id) => this.updateProject({ id, isArchived: true }));
  }

  unarchiveProjects(ids) {
    ids.forEach((id) => this.updateProject({ id, isArchived: false }));
  }

  createPayments(payments) {
    console.log('Creating payments ', payments)
    let outputData = payments.map((payment) => [
      payment.assignee,
      JSON.stringify({ ...payment, dateCreated: new Date().toISOString(), dateModified: new Date().toISOString(), modifiedBy: this.user?.name, createdBy: this.user?.name }),
      payment.projectNumber,
    ]); //data should be an array

    let lock = LockService.getScriptLock();
    try {
      if (!lock.tryLock(180000)) {
        throw new Error("Could not acquire lock");
      }
      this.shPayments.insertRowsBefore(2, outputData.length);
      this.shPayments
        .getRange(2, 1, outputData.length, outputData[0].length)
        .setValues(outputData);
    } finally {
      lock.releaseLock();
    }
  }

  updatePayment(updatedValues) {
    let payment = this.getPaymentById(updatedValues.id);
    if (!payment) throw "Payment not found";

    let updatedPayment = { ...payment, ...updatedValues, dateModified: new Date().toISOString(), modifiedBy: this.user?.name };

    let lock = LockService.getScriptLock();
    try {
      if (!lock.tryLock(180000)) {
        throw new Error("Could not acquire lock");
      }
    this.shPayments
      .getRange(payment._rowIndex, 2)
      .setValue(JSON.stringify(updatedPayment));
    }finally{
      lock.releaseLock()
    }
  }

  deletePayment(id) {
    let payment = this.getPaymentById(id);
    if (!payment) return;

    this.shPayments.deleteRow(payment._rowIndex);
  }

  createFBExpense(payment) {
    console.log('Creating FB Expense ', payment)
    let user = this.authApp.getUserByName(payment.assignee);
    if (!user) throw "User details not found";

    payment.expenseId = _createFBExpense_(payment, user);

    this.updatePayment(payment);
    return payment.expenseId;
  }

  createDropboxFolder(project) {
    try {
      let dropboxFolderName = `Project ${project.projectNumber} - ${project.projectName}`;
      var dropboxFolder = createDropBoxFolderAndGetLink(dropboxFolderName, this.user.email);
    } catch (e) {
      console.log(e);
    }

    project.projectFilesFolder = dropboxFolder;

    this.updateProject(project);

    return dropboxFolder;
  }

  createDriveFolderForProject(project) {
    let folderUrls = this.createDriveFolderStructure(project);

    project.projectFilesFolder = folderUrls.root
    project.draftingDropboxLink = folderUrls.arch
    project.engineeringDropboxLink = folderUrls.structural
    project.mepDropboxLink = folderUrls.mep
    project.civilDropboxLink = folderUrls.civil

    this.updateProject(project);

    return driveFolderUrl
  }

  createDriveFolderStructure(project) {
    let folders = {}

    let folderName = `Project ${project.projectNumber} - ${project.projectName}`;
    let driveRoot = DriveApp.getFolderById(_getIdFromUrl_(this.settings.projectsRootFolder));
    // Share with specific users without sending emails

    let now = new Date();
    let timestamp = Utilities.formatDate(now, Session.getScriptTimeZone(), "ddMMyyyy_HHmmss");

    // let projectFolder = driveRoot.createFolder(folderName + '_' + timestamp);
    let projectFolder = driveRoot.createFolder(folderName ); //removed the timestamp on 14thFeb

    // this.shareWithAllUsers(projectFolder)

    let subFolders = [
      `Client Folder - project ${project.projectNumber}`,
      `${project.projectNumber} - Old Archive Folder`,
    ];

    if(project.folderOptions?.drafter) subFolders.push(`${project.projectNumber} - Arch Folder`) //drafter
    if(project.folderOptions?.engg) subFolders.push(`${project.projectNumber} - Structural Folder`) //engg
    if(project.folderOptions?.mep) subFolders.push(`${project.projectNumber} - MEP Folder`) //mep
    if(project.folderOptions?.civil) subFolders.push(`${project.projectNumber} - Civil Folder`) //civil

    for (let folderName of subFolders) {
      let folder = projectFolder.createFolder(folderName);
      let folderId = folder.getId();

      if (folderName.startsWith('Client Folder - project ')) {
        // Share with anyone with link - can use regular DriveApp
        project.clientProjectFolder = folder.getUrl()
        folder.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.EDIT);
        if (project.clientEmail && project.folderOptions.sendClientEmail) {
          _sendEmail_('Project {{projectNumber}} - FILE UPLOADS REQUEST', project.clientEmail, project)
        }
      } else {
        if(folderName.includes('Arch Folder')) folders.arch = folder.getUrl()
        if(folderName.includes('Structural Folder')) folders.structural = folder.getUrl()
        if(folderName.includes('MEP Folder')) folders.mep = folder.getUrl()
        if(folderName.includes('Civil Folder')) folders.civil = folder.getUrl()
        if(folderName.includes('Old Archive Folder')) folders.archive = folder.getUrl()
          
        // this.shareWithAllUsers(folder)
      }
    }

    folders.root = projectFolder.getUrl()

    console.log(`Folders generated ${JSON.stringify(folders)}`)
    return folders
  }

  async shareWithAllUsers(folder) {
    let allUsers = this.settings.emailsWithEditAccess.split(',');
    // folder.addEditors(allUsers)
    //if notification is too much
      // Add write permission without sending notification emails
    for (const email of allUsers) {
      try {
        Drive.Permissions.create(
          {
            role: 'writer', 
            type: 'user',
            emailAddress: email 
          },
          folder.getId(), 
          {
            sendNotificationEmail: false 
          }
        );
      } catch (e) {
        console.log(`Error while adding ${email} ${e.details?.message}`)
      }
    }
  }
}

const doGet = (e) => new PublicApp().doGet(e);
const addNewUser = () => new User().addNewUser();
const resendInvitation = () => new User().resendInvitation();

const login = ({ token, data }) => new Auth().login({ token, ...data });

const include = (filename) => _include_(filename);

const onOpen = () => new PublicApp().onOpen();
const getSheetData = ({ token }) => new SecureApp(token).getSheetData();
const updateProject = ({ token, data }) => new SecureApp(token).updateProject(data);
const archiveProjects = ({ token, data }) => new SecureApp(token).archiveProjects(data);
const unarchiveProjects = ({ token, data }) => new SecureApp(token).unarchiveProjects(data);
const createProject = ({ token, data }) => new SecureApp(token).createProject(data);
const createDropboxFolder = ({ token, data }) => new SecureApp(token).createDriveFolderForProject(data) //createDropboxFolder(data); //we are creating drive folders as of Jan3,2025
const getNewProjectNumber = ({ token }) => new SecureApp(token).getNewProjectNumber();

const createPayments = ({ token, data }) => new SecureApp(token).createPayments(data);
const updatePayment = ({ token, data }) => new SecureApp(token).updatePayment(data);
const deletePayment = ({ token, data }) => new SecureApp(token).deletePayment(data);

//freshbooks functions
const createFBExpense = ({ token, data }) => new SecureApp(token).createFBExpense(data);
const getFBClient = ({ data }) => _getFBClient_(data);
const createFBClient = ({ data }) => _createFBClient_(data);
const createFBInvoice = ({ data }) => _createFBInvoice_(data);
const createFBProject = ({ data }) => _createFBProject_(data);
const createContract = ({ data }) => _createContract_(data);

const refreshMetadata = () => new PublicApp().refreshMetadata();
const getMetadata = () => new PublicApp().getMetadata();
const getContractMetadata = () => new PublicApp().getContractMetadata();

const metadataAutorefresh = () => {
  let triggers = ScriptApp.getProjectTriggers();
  triggers.forEach((trigger) => {
    if (trigger.getHandlerFunction() == "refreshMetadata") {
      ScriptApp.deleteTrigger(trigger);
    }
  });

  ScriptApp.newTrigger("refreshMetadata").timeBased().everyMinutes(30).create();
};

const formatPaymentSheet = () => {
  let ss = SpreadsheetApp.getActive()
  let sh = ss.getSheetByName('Payments')
  let data = sh.getDataRange().getValues()
  for (let i = 1; i < data.length; i++) {
    let json = JSON.parse(data[i][1])

    if (json.datePaid && json.datePaid.includes('/')) {
      var [month, day, year] = json.datePaid.split('/');
      month = month.padStart(2, '0');
      day = day.padStart(2, '0');
      json.datePaid = `${year}-${month}-${day}`;
    }

    if (json.datePaid2 && json.datePaid2.includes('/')) {
      var [month, day, year] = json.datePaid2.split('/');
      month = month.padStart(2, '0');
      day = day.padStart(2, '0');
      json.datePaid2 = `${year}-${month}-${day}`;
    }

    // Convert back to JSON string and update the cell
    data[i][1] = JSON.stringify(json);
  }

  ss.getSheetByName('testP').getRange(1, 1, data.length, data[0].length).setValues(data)
}
